services:
  frontend:
    build:
      context: ../pangandaran-ai_chatbot
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=https://acclimate-sacrament-musket.ngrok-free.dev
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=https://acclimate-sacrament-musket.ngrok-free.dev
    restart: unless-stopped
